services:
  - type: web
    name: videovic
    env: python
    buildCommand: |
        pip install -r requirements.txt
        python manage.py collectstatic --noinput

    plan: free
    startCommand: "daphne -b 0.0.0.0 -p $PORT videovic.asgi:application"
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: videovic.settings
      - key: SECRET_KEY
        value: a3r_9@z!t8p+28x*1v5gk#z8wjr&qnby6du^j+3=c5w!s&li43
      - key: DEBUG
        value: False
